### ISSUE TITLE
Gulp 4 的文档准备翻译吗？

### ISSUE THREAD

**Issue by cssmagic** [lisposter/gulp-docs-zh-cn#2]
[Gulp 的 `4.0` 分支](https://github.com/gulpjs/gulp/blob/4.0/docs) 有新版文档。

我可以帮忙啊 :smiley:

**Comment by lisposter** [comment]
可以有，欢迎参与

**Comment by lisposter** [comment]
@cssmagic 这边也开个 4.0 分支跟进官方文档，已经添加你为 Collaborator，方便操作 :beers:

**Comment by lisposter** [comment]
@cssmagic 这边也开个 4.0 分支跟进官方文档，已经添加你为 Collaborator，方便操作 :beers:

**Comment by lisposter** [comment]
@cssmagic 这边也开个 4.0 分支跟进官方文档，已经添加你为 Collaborator 了，方便操作 :beers:

**Comment by cssmagic** [comment]
好的，开动！

随便提一句，我翻译的习惯是保留原文，比如 [这一篇](https://github.com/baixing/FE-Blog/issues/6)。这样不仅方便读者对照原文，而且也方便对比原文的更新。你觉得这种形式如何？

**Comment by lisposter** [comment]
这种方式不错，但是感觉不适合文档这种地方，看上去会有点乱，不流畅。这里还是和其他语种保持一致，直接放译文好了

**Comment by lisposter** [comment]
开个进度 issue 吧，记录下你正在翻译的文档，以免翻重了，忙完这阵我也会来翻译，另外，注意纪录下翻译时候的官方文档时间点，官方不希望有过时的文档，需要不断跟进。

**Comment by cssmagic** [comment]
好的。

**Comment by cssmagic** [comment]
我按照自己的习惯先翻译了一篇 [API 文档](https://github.com/cssmagic/blog/issues/55)，放在自己博客里了。可以拿来直接用或随便改，署不署名都没关系。

**Comment by lisposter** [comment]
@cssmagic :+1: 很棒，考虑放到 4.0 分支上吧

**Comment by cssmagic** [comment]
好的，我先复制过来。等啥时有空再去掉原文。
